name: CI
on: [push]

jobs:
  test_cuda:
    name: TestCuda
    runs-on: ubuntu-latest
    container: nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
    steps:
    - name: Run nvcc --version
      run: nvcc --version
